name: project-azua
channels:
  - pytorch
  - defaults
  # Do we need conda-forge?
  - conda-forge
dependencies:
  - python==3.8.2
  - tqdm==4.50.2
  # ML packages
  - numpy==1.19.2
  - pytorch==1.7.0
  - cudatoolkit=10.2
  - scipy==1.5.2
  - scikit-learn==0.23.2
  - pandas==1.1.3
  - matplotlib==3.3.2
  - torchvision>=0.8.0
  - seaborn==0.11.0
  - tensorboard==2.3.0
  # Dev tools (testing, static analysis, styling etc.):
  - pytest==6.1.1
  - pytest-cov==2.10.1
  # TODO: update mypy to newer version once available. We need this feature https://github.com/python/mypy/issues/6385 
  # in order not to need to specify __init__.py file in every single directory we want to run mypy for.
  - mypy==0.790
  - gitpython==3.1.11
  - black==19.10b0
  - flake8==3.8.4
  - pre-commit==2.9.3
  - pip==20.2.4
  - pip:
    # ML packages
    - torch-scatter==2.0.5+cu102
    - --find-links https://pytorch-geometric.com/whl/torch-1.7.0.html
    - torch-sparse==0.6.8+cu102
    - --find-links https://pytorch-geometric.com/whl/torch-1.7.0.html
    - torch-geometric==1.6.3
    - transformers==4.4.2
    - sentence_transformers==1.0.4
    # Note: we will not need it once numpy 1.20, which contains stubs, is released (and we move to it)
    - git+https://github.com/numpy/numpy-stubs
    - dppy==0.3.1
    # DI framework
    - dependency_injector==4.34.2
